// ── Runico changelog + app description ───────────────────────────────────────
// Static, authored content (plain JS, loaded before app.jsx — like i18n.js).
// Shown on the About page, reachable from the version badge (bottom-left) and
// from Settings → About.
//
// To cut a release: add an entry to the TOP of RUNICO_CHANGELOG (newest first).
// Each change's `type` must be one of: 'feature' | 'fix' | 'enhancement' | 'security'.
// Keep the newest release's `version` in sync with package.json "version" and the
// APP_VERSION constant in app.jsx.
//
// This is product content, not interface chrome, so it is authored in English and
// is not run through the i18n layer (mirroring how card/source content is handled).

window.RUNICO_ABOUT = {
  tagline: {"en":"Magical runes for your learning.","pt-BR":"Runas mágicas para o seu aprendizado.","pt-PT":"Runas mágicas para a tua aprendizagem.","es":"Runas mágicas para tu aprendizaje.","ru":"Магические руны для вашего обучения.","it":"Rune magiche per il tuo apprendimento.","zh":"为你的学习注入神奇符文。"},
  description: [
    {"en":"Runico turns anything you're learning into flashcards and helps you practice them — recall the answer, reveal it, then Continue or Pause, with no grading scales to fuss over.","pt-BR":"O Runico transforma qualquer coisa que você esteja aprendendo em flashcards e ajuda você a praticá-los — relembre a resposta, revele-a e então Continue ou Pause, sem escalas de avaliação com que se preocupar.","pt-PT":"O Runico transforma tudo aquilo que estás a aprender em cartões e ajuda-te a praticá-los — recorda a resposta, revela-a e depois Continua ou Pausa, sem escalas de classificação com que te preocupares.","es":"Runico convierte cualquier cosa que estés aprendiendo en tarjetas y te ayuda a practicarlas: recuerda la respuesta, revélala y luego Continúa o Pausa, sin escalas de calificación con las que lidiar.","ru":"Runico превращает всё, что вы изучаете, в карточки и помогает их отрабатывать — вспомните ответ, откройте его, а затем нажмите «Продолжить» или «Пауза», без всяких шкал оценок, в которых нужно разбираться.","it":"Runico trasforma qualsiasi cosa tu stia imparando in flashcard e ti aiuta a esercitarti — richiama la risposta, rivelala, poi Continua o Metti in pausa, senza scale di valutazione di cui preoccuparti.","zh":"Runico 把你正在学习的任何内容变成抽认卡，并帮你练习——回想答案，揭示答案，然后选择继续或暂停，无需纠结于评分等级。"},
    {"en":"Your library is organized into subjects, folders, and topics you can navigate in a column browser. Per-session accuracy charts show whether a topic is trending up — reporting only, never grading. Drop in a page, screenshot, or notes and Runico drafts cards for you to review, including image-occlusion cards that mask regions of a figure.","pt-BR":"Sua biblioteca é organizada em matérias, pastas e tópicos que você pode navegar em um navegador de colunas. Gráficos de acerto por sessão mostram se um tópico está em ascensão — apenas relatórios, nunca avaliação. Solte uma página, captura de tela ou anotações e o Runico cria rascunhos de cards para você revisar, incluindo cards de oclusão de imagem que mascaram regiões de uma figura.","pt-PT":"A tua biblioteca está organizada em disciplinas, pastas e tópicos que podes percorrer num navegador de colunas. Os gráficos de precisão por sessão mostram se um tópico está a melhorar — apenas para informação, nunca para classificar. Deixa cair uma página, captura de ecrã ou notas e o Runico esboça cartões para reveres, incluindo cartões de oclusão de imagem que tapam regiões de uma figura.","es":"Tu biblioteca se organiza en materias, carpetas y temas que puedes navegar en un explorador de columnas. Los gráficos de precisión por sesión muestran si un tema va al alza: solo informan, nunca califican. Añade una página, una captura de pantalla o apuntes y Runico redacta tarjetas para que las revises, incluidas tarjetas de oclusión de imagen que ocultan regiones de una figura.","ru":"Ваша библиотека организована по предметам, папкам и темам, по которым можно перемещаться в колоночном браузере. Графики точности по сессиям показывают, идёт ли тема в гору, — только отчётность, никаких оценок. Добавьте страницу, скриншот или заметки, и Runico набросает для вас карточки на проверку, включая карточки с закрытием областей изображения, которые маскируют участки рисунка.","it":"La tua libreria è organizzata in materie, cartelle e argomenti che puoi esplorare in un browser a colonne. I grafici di accuratezza per sessione mostrano se un argomento è in crescita — solo report, mai valutazioni. Inserisci una pagina, uno screenshot o degli appunti e Runico crea per te delle bozze di card da rivedere, comprese le card a occlusione di immagine che mascherano regioni di una figura.","zh":"你的资料库按学科、文件夹和主题进行整理，可在分栏浏览器中浏览。各次练习的准确率图表会显示某个主题是否呈上升趋势——仅作记录，绝不评分。放入一个页面、截图或笔记，Runico 就会为你起草卡片供你审阅，包括遮盖图中部分区域的图像遮挡卡。"},
    {"en":"On the desktop, all your data lives in a local save file you own, and your OpenRouter key is stored in the operating-system keychain — never in the page.","pt-BR":"No desktop, todos os seus dados ficam em um arquivo de salvamento local que pertence a você, e sua chave do OpenRouter é armazenada no chaveiro do sistema operacional — nunca na página.","pt-PT":"No computador, todos os teus dados ficam num ficheiro de gravação local que te pertence, e a tua chave do OpenRouter é guardada no porta-chaves do sistema operativo — nunca na página.","es":"En el escritorio, todos tus datos viven en un archivo de guardado local que te pertenece, y tu clave de OpenRouter se almacena en el llavero del sistema operativo, nunca en la página.","ru":"На компьютере все ваши данные хранятся в локальном файле сохранения, который принадлежит вам, а ваш ключ OpenRouter хранится в связке ключей операционной системы — никогда на странице.","it":"Sul desktop, tutti i tuoi dati risiedono in un file di salvataggio locale di tua proprietà, e la tua chiave OpenRouter è memorizzata nel keychain del sistema operativo — mai nella pagina.","zh":"在桌面端，你的所有数据都保存在你自己拥有的本地存档文件中，你的 OpenRouter 密钥存储在操作系统钥匙串里——绝不存于页面中。"},
  ],
};

window.RUNICO_CHANGELOG = [
  {
    version: '1.1.0',
    date: '2026-06-14',
    summary: {"en":"Merge another library into the one you're working in — folders, topics, cards, and study history fold together, with a step to resolve any duplicate cards.","pt-BR":"Mescle outra biblioteca à que você está usando — pastas, tópicos, cards e histórico de estudo se juntam, com uma etapa para resolver cards duplicados.","pt-PT":"Une outra biblioteca à que estás a usar — pastas, tópicos, cartões e histórico de estudo juntam-se, com um passo para resolver cartões duplicados.","es":"Combina otra biblioteca con la que estás usando: carpetas, temas, tarjetas e historial de estudio se unen, con un paso para resolver tarjetas duplicadas.","ru":"Объедините другую библиотеку с текущей — папки, темы, карточки и история занятий сливаются воедино, с шагом для разрешения повторяющихся карточек.","it":"Unisci un'altra libreria a quella che stai usando — cartelle, argomenti, card e cronologia di studio si fondono, con un passaggio per risolvere le card duplicate.","zh":"把另一个卡片库合并到你正在使用的库中——文件夹、主题、卡片和练习记录融合在一起，并提供解决重复卡片的步骤。"},
    entries: [
      { type: 'feature', text: {"en":"Merge a library: pick a second .runico file and Runico folds it into the open one — folders and topics with matching names combine, everything else is added, and your study history comes along.","pt-BR":"Mescle uma biblioteca: escolha um segundo arquivo .runico e o Runico o integra ao que está aberto — pastas e tópicos com nomes iguais se combinam, o restante é adicionado, e seu histórico de estudo vem junto.","pt-PT":"Une uma biblioteca: escolhe um segundo ficheiro .runico e o Runico integra-o no que está aberto — pastas e tópicos com nomes iguais combinam-se, o resto é adicionado, e o teu histórico de estudo vem junto.","es":"Combina una biblioteca: elige un segundo archivo .runico y Runico lo integra en el abierto: las carpetas y temas con el mismo nombre se combinan, el resto se añade y tu historial de estudio viene incluido.","ru":"Объединение библиотек: выберите второй файл .runico, и Runico вольёт его в открытый — папки и темы с совпадающими именами объединяются, остальное добавляется, и история занятий переносится вместе с ними.","it":"Unisci una libreria: scegli un secondo file .runico e Runico lo integra in quello aperto — cartelle e argomenti con lo stesso nome si combinano, il resto viene aggiunto e la tua cronologia di studio viene con essi.","zh":"合并卡片库：选择第二个 .runico 文件，Runico 会将其并入当前打开的库——同名的文件夹和主题会合并，其余内容会被添加，你的练习记录也会一并带入。"} },
      { type: 'feature', text: {"en":"Resolve duplicates while merging: a card that already exists in the same place is shown side by side with the incoming one so you can compare them, then decide per card — keep both, edit the incoming one, or skip it (its study history merges into the card you keep).","pt-BR":"Resolva duplicatas ao mesclar: um card que já existe no mesmo lugar é mostrado lado a lado com o que está chegando para você comparar, e então você decide card a card — manter ambos, editar o que está chegando ou ignorá-lo (o histórico de estudo dele é mesclado ao card que você mantém).","pt-PT":"Resolve duplicados ao unir: um cartão que já existe no mesmo sítio é mostrado lado a lado com o que está a chegar para poderes comparar, e depois decides cartão a cartão — manter ambos, editar o que está a chegar ou ignorá-lo (o histórico de estudo dele junta-se ao cartão que manténs).","es":"Resuelve duplicados al combinar: una tarjeta que ya existe en el mismo lugar se muestra junto a la entrante para que las compares, y luego decides tarjeta por tarjeta: conservar ambas, editar la entrante u omitirla (su historial de estudio se fusiona con la tarjeta que conservas).","ru":"Разрешение дубликатов при объединении: карточка, которая уже есть в том же месте, показывается рядом с входящей для сравнения, и вы решаете по каждой — оставить обе, изменить входящую или пропустить её (её история занятий вливается в оставленную карточку).","it":"Risolvi i duplicati durante l'unione: una card che esiste già nello stesso punto viene mostrata fianco a fianco con quella in arrivo per confrontarle, poi decidi card per card — tieni entrambe, modifica quella in arrivo oppure saltala (la sua cronologia di studio si fonde con la card che tieni).","zh":"合并时解决重复：已存在于同一位置的卡片会与传入卡片并排显示以便对比，然后你可逐张决定——两者都保留、编辑传入卡片或跳过（其练习记录会并入你保留的卡片）。"} },
    ],
  },
  {
    version: '1.0.1',
    date: '2026-06-14',
    summary: {"en":"A mobile fix release: phones and tablets now lay out and respond to touch correctly.","pt-BR":"Um lançamento de correções para celular: telefones e tablets agora se ajustam e respondem ao toque corretamente.","pt-PT":"Uma versão de correções para telemóvel: telemóveis e tablets agora ajustam-se e respondem ao toque corretamente.","es":"Una versión de correcciones para móvil: los teléfonos y tablets ahora se distribuyen y responden al toque correctamente.","ru":"Выпуск с исправлениями для мобильных устройств: телефоны и планшеты теперь корректно отображаются и реагируют на касания.","it":"Una release di correzioni per il mobile: telefoni e tablet ora si dispongono e rispondono al tocco correttamente.","zh":"移动端修复版本：手机和平板现在能够正确布局并响应触控。"},
    entries: [
      { type: 'fix', text: {"en":"Mobile layout: the top navigation no longer overflows and shrinks the whole page on phones — it becomes an icon-only app bar so every action fits, and the performance chart, stat cards, and drill-down are legible again.","pt-BR":"Layout no celular: a navegação superior não transborda mais nem encolhe a página inteira no telefone — ela vira uma barra de aplicativo só com ícones, então todas as ações cabem, e o gráfico de desempenho, os cards de estatísticas e o detalhamento ficam legíveis de novo.","pt-PT":"Disposição no telemóvel: a navegação superior já não transborda nem encolhe a página inteira no telemóvel — passa a ser uma barra de aplicação só com ícones, por isso todas as ações cabem, e o gráfico de desempenho, os cartões de estatísticas e o detalhe voltam a ser legíveis.","es":"Disposición en móvil: la navegación superior ya no se desborda ni encoge toda la página en el teléfono: se convierte en una barra de aplicación solo con iconos, así que todas las acciones caben, y el gráfico de rendimiento, las tarjetas de estadísticas y el desglose vuelven a ser legibles.","ru":"Вёрстка на мобильных: верхняя навигация больше не выходит за края и не сжимает всю страницу на телефоне — она превращается в панель только из значков, поэтому все действия помещаются, а график результатов, карточки статистики и детализация снова читаемы.","it":"Layout su mobile: la navigazione superiore non va più in overflow né rimpicciolisce l'intera pagina sul telefono — diventa una barra app solo con icone, così tutte le azioni ci stanno, e il grafico delle prestazioni, le card delle statistiche e l'analisi dettagliata tornano leggibili.","zh":"移动端布局：顶部导航在手机上不再溢出并把整个页面缩小——它会变成纯图标的应用栏，使所有操作都能容纳，性能图表、统计卡片和细分视图也重新清晰可读。"} },
      { type: 'fix', text: {"en":"Folder and topic actions (Rename, Move, Copy, Delete, Paste) are now reachable by tap on touch devices — they were previously hover-only and unreachable on a phone.","pt-BR":"As ações de pastas e tópicos (Renomear, Mover, Copiar, Excluir, Colar) agora podem ser acessadas por toque em dispositivos de toque — antes só apareciam ao passar o cursor e ficavam inacessíveis no celular.","pt-PT":"As ações de pastas e tópicos (Mudar o nome, Mover, Copiar, Eliminar, Colar) agora estão acessíveis por toque em dispositivos táteis — antes apareciam só ao passar o cursor e ficavam inacessíveis no telemóvel.","es":"Las acciones de carpetas y temas (Renombrar, Mover, Copiar, Eliminar, Pegar) ahora se pueden usar tocando en dispositivos táctiles: antes solo aparecían al pasar el cursor y eran inaccesibles en el teléfono.","ru":"Действия с папками и темами (Переименовать, Переместить, Копировать, Удалить, Вставить) теперь доступны по касанию на сенсорных устройствах — раньше они появлялись только при наведении и были недоступны на телефоне.","it":"Le azioni su cartelle e argomenti (Rinomina, Sposta, Copia, Elimina, Incolla) ora sono raggiungibili con il tocco sui dispositivi touch — prima comparivano solo al passaggio del cursore ed erano irraggiungibili sul telefono.","zh":"文件夹和主题的操作（重命名、移动、复制、删除、粘贴）现在可在触控设备上通过点按使用——此前它们仅在悬停时出现，在手机上无法访问。"} },
      { type: 'fix', text: {"en":"Browse view centers the last-opened card on phones instead of scrolling to the screen edge.","pt-BR":"A visualização de navegação centraliza o último card aberto no celular em vez de rolar até a borda da tela.","pt-PT":"A vista de navegação centra o último cartão aberto no telemóvel em vez de deslocar até à margem do ecrã.","es":"La vista de navegación centra la última tarjeta abierta en el teléfono en lugar de desplazarse hasta el borde de la pantalla.","ru":"Режим обзора центрирует последнюю открытую карточку на телефоне вместо прокрутки к краю экрана.","it":"La vista di navigazione centra l'ultima card aperta sul telefono invece di scorrere fino al bordo dello schermo.","zh":"浏览视图在手机上会将最后打开的卡片居中，而不是滚动到屏幕边缘。"} },
      { type: 'enhancement', text: {"en":"Bigger tap targets across the navigation, list actions, and the image-occlusion editor; on touch the performance chart uses tap-to-toggle tooltips.","pt-BR":"Alvos de toque maiores na navegação, nas ações de lista e no editor de oclusão de imagem; no toque, o gráfico de desempenho usa dicas que aparecem ao tocar.","pt-PT":"Alvos de toque maiores na navegação, nas ações de lista e no editor de oclusão de imagem; no toque, o gráfico de desempenho usa dicas que surgem ao tocar.","es":"Áreas de toque más grandes en la navegación, las acciones de lista y el editor de oclusión de imagen; al tocar, el gráfico de rendimiento usa tooltips que se muestran al pulsar.","ru":"Увеличены области касания в навигации, действиях со списками и редакторе закрытия изображений; на сенсорных экранах график результатов использует всплывающие подсказки по касанию.","it":"Aree di tocco più grandi nella navigazione, nelle azioni delle liste e nell'editor a occlusione di immagine; al tocco, il grafico delle prestazioni usa tooltip che compaiono al tap.","zh":"导航、列表操作和图像遮挡编辑器中的点按目标更大；在触控时，性能图表采用点按切换的提示框。"} },
      { type: 'fix', text: {"en":"Keyboard shortcut hints (Enter, X, Esc, Space) are hidden on touch devices, which have no keyboard — the same actions stay reachable via the on-screen buttons.","pt-BR":"As dicas de atalho de teclado (Enter, X, Esc, Espaço) ficam ocultas em dispositivos de toque, que não têm teclado — as mesmas ações continuam acessíveis pelos botões na tela.","pt-PT":"As dicas de atalho de teclado (Enter, X, Esc, Espaço) ficam ocultas em dispositivos táteis, que não têm teclado — as mesmas ações continuam acessíveis pelos botões no ecrã.","es":"Las indicaciones de atajos de teclado (Enter, X, Esc, Espacio) se ocultan en dispositivos táctiles, que no tienen teclado: las mismas acciones siguen disponibles mediante los botones en pantalla.","ru":"Подсказки клавиатурных сочетаний (Enter, X, Esc, Пробел) скрыты на сенсорных устройствах без клавиатуры — те же действия остаются доступны через экранные кнопки.","it":"I suggerimenti delle scorciatoie da tastiera (Enter, X, Esc, Spazio) sono nascosti sui dispositivi touch, privi di tastiera — le stesse azioni restano raggiungibili tramite i pulsanti a schermo.","zh":"键盘快捷键提示（Enter、X、Esc、空格）在没有键盘的触控设备上隐藏——相同的操作仍可通过屏幕上的按钮使用。"} },
    ],
  },
  {
    version: '1.0.0',
    date: '2026-06-05',
    summary: {"en":"The first stable release — the full Runico feature set, working with files you own, as a local-first desktop app and a web build.","pt-BR":"O primeiro lançamento estável — o conjunto completo de recursos do Runico, funcionando com arquivos que pertencem a você, como um aplicativo de desktop local-first e uma versão web.","pt-PT":"A primeira versão estável — o conjunto completo de funcionalidades do Runico, a funcionar com ficheiros que te pertencem, como uma aplicação de computador local-first e uma versão web.","es":"La primera versión estable: el conjunto completo de funciones de Runico, funcionando con archivos que te pertenecen, como una aplicación de escritorio local-first y una versión web.","ru":"Первый стабильный релиз — полный набор возможностей Runico, работающий с файлами, которые принадлежат вам, как локальное настольное приложение и веб-сборка.","it":"La prima release stabile — l'intero set di funzionalità di Runico, che lavora con file di tua proprietà, come app desktop local-first e build web.","zh":"首个稳定版本——完整的 Runico 功能集，配合你自己拥有的文件运行，既是本地优先的桌面应用，也提供网页版本。"},
    entries: [
      { type: 'feature', text: {"en":"Study sessions with a reveal-then-Continue/Pause flow and no grading scales.","pt-BR":"Sessões de estudo com um fluxo de revelar-e-então-Continuar/Pausar e sem escalas de avaliação.","pt-PT":"Sessões de estudo com um fluxo de revelar-e-depois-Continuar/Pausar e sem escalas de classificação.","es":"Sesiones de estudio con un flujo de revelar y luego Continuar/Pausar, y sin escalas de calificación.","ru":"Учебные сессии с потоком «открыть, затем Продолжить/Пауза» и без шкал оценок.","it":"Sessioni di studio con un flusso rivela-poi-Continua/Metti in pausa e senza scale di valutazione.","zh":"练习采用先揭示再继续/暂停的流程，没有评分等级。"} },
      { type: 'feature', text: {"en":"Pick up where you left off: the home view remembers your last session and the cards remaining.","pt-BR":"Retome de onde parou: a tela inicial lembra sua última sessão e os cards restantes.","pt-PT":"Retoma de onde ficaste: a vista inicial recorda a tua última sessão e os cartões em falta.","es":"Retoma donde lo dejaste: la vista de inicio recuerda tu última sesión y las tarjetas que quedan.","ru":"Продолжайте с того места, где остановились: на главном экране запоминается ваша последняя сессия и количество оставшихся карточек.","it":"Riprendi da dove avevi lasciato: la schermata principale ricorda la tua ultima sessione e le card rimanenti.","zh":"从上次中断处继续：主页视图会记住你上一次的练习以及剩余的卡片。"} },
      { type: 'feature', text: {"en":"Column browser for navigating subjects, folders, and topics, then practicing any one of them.","pt-BR":"Navegador de colunas para percorrer matérias, pastas e tópicos e então praticar qualquer um deles.","pt-PT":"Navegador de colunas para percorrer disciplinas, pastas e tópicos e depois praticar qualquer um deles.","es":"Explorador de columnas para navegar entre materias, carpetas y temas, y luego practicar cualquiera de ellos.","ru":"Колоночный браузер для перемещения по предметам, папкам и темам, а затем отработки любого из них.","it":"Browser a colonne per navigare tra materie, cartelle e argomenti, e poi esercitarti su uno qualsiasi di essi.","zh":"分栏浏览器，用于浏览学科、文件夹和主题，然后练习其中任意一项。"} },
      { type: 'feature', text: {"en":"Reorganize folders and topics by drag-and-drop or cut/copy-and-paste — move a folder with everything inside, or copy it into another folder.","pt-BR":"Reorganize pastas e tópicos arrastando e soltando ou recortando/copiando e colando — mova uma pasta com tudo que há dentro, ou copie-a para outra pasta.","pt-PT":"Reorganiza pastas e tópicos por arrastar e largar ou cortar/copiar e colar — move uma pasta com tudo o que está lá dentro, ou copia-a para outra pasta.","es":"Reorganiza carpetas y temas arrastrando y soltando o cortando/copiando y pegando: mueve una carpeta con todo lo que contiene, o cópiala en otra carpeta.","ru":"Реорганизуйте папки и темы перетаскиванием или через вырезать/копировать и вставить — переместите папку со всем её содержимым или скопируйте её в другую папку.","it":"Riorganizza cartelle e argomenti con il trascinamento o taglia/copia-e-incolla — sposta una cartella con tutto il suo contenuto, oppure copiala in un'altra cartella.","zh":"通过拖放或剪切/复制粘贴重新整理文件夹和主题——连同内部的所有内容一起移动文件夹，或将其复制到另一个文件夹中。"} },
      { type: 'feature', text: {"en":"Trash bin: deleting a folder, topic, or card moves it to a recoverable trash, where you can restore it to its place, delete it forever, or empty the trash.","pt-BR":"Lixeira: excluir uma pasta, tópico ou card o move para uma lixeira recuperável, onde você pode restaurá-lo ao seu lugar, excluí-lo definitivamente ou esvaziar a lixeira.","pt-PT":"Reciclagem: ao eliminar uma pasta, tópico ou cartão, este é movido para uma reciclagem recuperável, onde o podes restaurar para o seu lugar, eliminar definitivamente ou esvaziar a reciclagem.","es":"Papelera: al eliminar una carpeta, un tema o una tarjeta, se mueven a una papelera recuperable, donde puedes restaurarlos a su lugar, eliminarlos para siempre o vaciar la papelera.","ru":"Корзина: при удалении папки, темы или карточки они перемещаются в корзину с возможностью восстановления, где вы можете вернуть их на место, удалить навсегда или очистить корзину.","it":"Cestino: eliminando una cartella, un argomento o una card, questa viene spostata in un cestino recuperabile, dove puoi ripristinarla al suo posto, eliminarla definitivamente o svuotare il cestino.","zh":"回收站：删除文件夹、主题或卡片会将其移入可恢复的回收站，你可以将它还原到原位、永久删除，或清空回收站。"} },
      { type: 'feature', text: {"en":"Track your progress with per-session accuracy charts and a drill-down to any single card.","pt-BR":"Acompanhe seu progresso com gráficos de acerto por sessão e um detalhamento até qualquer card individual.","pt-PT":"Acompanha o teu progresso com gráficos de precisão por sessão e um detalhe até qualquer cartão individual.","es":"Sigue tu progreso con gráficos de precisión por sesión y un desglose hasta cualquier tarjeta individual.","ru":"Отслеживайте свой прогресс с помощью графиков точности по сессиям и детализации вплоть до любой отдельной карточки.","it":"Tieni traccia dei tuoi progressi con grafici di accuratezza per sessione e un'analisi dettagliata fino alla singola card.","zh":"通过各次练习的准确率图表追踪你的进度，并可深入查看任意单张卡片。"} },
      { type: 'feature', text: {"en":"Generate cards from pasted text, screenshots, or notes via OpenRouter, then review the drafts before keeping them.","pt-BR":"Gere cards a partir de texto colado, capturas de tela ou anotações via OpenRouter e então revise os rascunhos antes de mantê-los.","pt-PT":"Gera cartões a partir de texto colado, capturas de ecrã ou notas através do OpenRouter e depois revê os esboços antes de os manteres.","es":"Genera tarjetas a partir de texto pegado, capturas de pantalla o apuntes mediante OpenRouter, y luego revisa los borradores antes de conservarlos.","ru":"Создавайте карточки из вставленного текста, скриншотов или заметок через OpenRouter, а затем просматривайте черновики, прежде чем их сохранить.","it":"Genera card da testo incollato, screenshot o appunti tramite OpenRouter, poi rivedi le bozze prima di conservarle.","zh":"通过 OpenRouter 从粘贴的文本、截图或笔记生成卡片，然后在保留之前审阅草稿。"} },
      { type: 'feature', text: {"en":"Image-occlusion cards: draw, drag, and resize masks over a figure, and re-crop from the full original image.","pt-BR":"Cards de oclusão de imagem: desenhe, arraste e redimensione máscaras sobre uma figura, e recorte novamente a partir da imagem original completa.","pt-PT":"Cartões de oclusão de imagem: desenha, arrasta e redimensiona máscaras sobre uma figura e recorta novamente a partir da imagem original completa.","es":"Tarjetas de oclusión de imagen: dibuja, arrastra y cambia el tamaño de las máscaras sobre una figura, y recorta de nuevo desde la imagen original completa.","ru":"Карточки с закрытием областей изображения: рисуйте, перетаскивайте и изменяйте размер масок поверх рисунка, а также заново кадрируйте из полного исходного изображения.","it":"Card a occlusione di immagine: disegna, trascina e ridimensiona le maschere su una figura, e ritaglia di nuovo dall'immagine originale completa.","zh":"图像遮挡卡：在图上绘制、拖动并调整遮罩大小，还可从完整的原图重新裁剪。"} },
      { type: 'feature', text: {"en":"“Use my own AI”: copy the generation prompt, paste the result back, and Runico builds the cards — including image-occlusion cards with the masks placed for you.","pt-BR":"“Use my own AI”: copie o prompt de geração, cole o resultado de volta e o Runico monta os cards — incluindo cards de oclusão de imagem com as máscaras já posicionadas para você.","pt-PT":"“Use my own AI”: copia o prompt de geração, cola o resultado de volta e o Runico cria os cartões — incluindo cartões de oclusão de imagem com as máscaras já colocadas por ti.","es":"“Usar mi propia IA”: copia el prompt de generación, pega el resultado de vuelta y Runico crea las tarjetas, incluidas tarjetas de oclusión de imagen con las máscaras colocadas por ti.","ru":"«Use my own AI»: скопируйте промпт генерации, вставьте результат обратно, и Runico создаст карточки — включая карточки с закрытием областей изображения с уже расставленными для вас масками.","it":"“Use my own AI”: copia il prompt di generazione, incolla il risultato e Runico crea le card — comprese le card a occlusione di immagine con le maschere già posizionate per te.","zh":"“使用我自己的 AI”：复制生成提示词，将结果粘贴回来，Runico 便会构建卡片——包括已为你放置好遮罩的图像遮挡卡。"} },
      { type: 'feature', text: {"en":"A per-model cost estimate (cards per $1) when choosing a generation model.","pt-BR":"Uma estimativa de custo por modelo (cards por $1) ao escolher um modelo de geração.","pt-PT":"Uma estimativa de custo por modelo (cartões por $1) ao escolher um modelo de geração.","es":"Una estimación de coste por modelo (tarjetas por $1) al elegir un modelo de generación.","ru":"Оценка стоимости по каждой модели (карточек на $1) при выборе модели генерации.","it":"Una stima dei costi per modello (card per $1) quando scegli un modello di generazione.","zh":"在选择生成模型时，提供每个模型的成本估算（每 $1 可生成的卡片数）。"} },
      { type: 'feature', text: {"en":"See-the-source view that shows the original material with the studied term highlighted.","pt-BR":"Visualização que mostra a fonte, exibindo o material original com o termo estudado destacado.","pt-PT":"Vista ver-a-origem que mostra o material original com o termo estudado realçado.","es":"Vista de ver-la-fuente que muestra el material original con el término estudiado resaltado.","ru":"Режим просмотра источника, который показывает исходный материал с подсвеченным изучаемым термином.","it":"Vista vedi-la-fonte che mostra il materiale originale con il termine studiato evidenziato.","zh":"查看来源视图，显示原始素材并高亮所学的术语。"} },
      { type: 'feature', text: {"en":"Work in files you own: open a library file to start, or create a new one — your folders, cards, and pictures all live in that file, and every change is saved to it automatically.","pt-BR":"Trabalhe em arquivos que pertencem a você: abra um arquivo de biblioteca para começar, ou crie um novo — suas pastas, cards e imagens ficam todos nesse arquivo, e cada alteração é salva nele automaticamente.","pt-PT":"Trabalha em ficheiros que te pertencem: abre um ficheiro de biblioteca para começar, ou cria um novo — as tuas pastas, cartões e imagens ficam todos nesse ficheiro, e cada alteração é guardada nele automaticamente.","es":"Trabaja con archivos que te pertenecen: abre un archivo de biblioteca para empezar, o crea uno nuevo: tus carpetas, tarjetas e imágenes viven todas en ese archivo, y cada cambio se guarda en él automáticamente.","ru":"Работайте с файлами, которые принадлежат вам: откройте файл библиотеки, чтобы начать, или создайте новый — ваши папки, карточки и картинки хранятся в этом файле, и каждое изменение сохраняется в нём автоматически.","it":"Lavora con file di tua proprietà: apri un file di libreria per iniziare, oppure creane uno nuovo — le tue cartelle, card e immagini risiedono tutte in quel file, e ogni modifica vi viene salvata automaticamente.","zh":"使用你自己拥有的文件：打开一个资料库文件开始，或新建一个——你的文件夹、卡片和图片都保存在该文件中，每次更改都会自动保存到其中。"} },
      { type: 'feature', text: {"en":"Light, Warm, and Dark canvas themes and a per-language interface in seven languages.","pt-BR":"Temas de tela Claro, Quente e Escuro e uma interface por idioma em sete idiomas.","pt-PT":"Temas de tela Claro, Quente e Escuro e uma interface por idioma em sete idiomas.","es":"Temas de lienzo Claro, Cálido y Oscuro y una interfaz por idioma en siete lenguas.","ru":"Светлая, Тёплая и Тёмная темы холста и интерфейс на семи языках с переключением по языкам.","it":"Temi della tela Chiaro, Caldo e Scuro e un'interfaccia per lingua in sette lingue.","zh":"浅色、暖色和深色画布主题，以及支持七种语言的多语言界面。"} },
      { type: 'feature', text: {"en":"Desktop app for macOS, Windows, and Linux that runs fully offline.","pt-BR":"Aplicativo de desktop para macOS, Windows e Linux que funciona totalmente offline.","pt-PT":"Aplicação de computador para macOS, Windows e Linux que funciona totalmente offline.","es":"Aplicación de escritorio para macOS, Windows y Linux que funciona completamente sin conexión.","ru":"Настольное приложение для macOS, Windows и Linux, работающее полностью офлайн.","it":"App desktop per macOS, Windows e Linux che funziona completamente offline.","zh":"适用于 macOS、Windows 和 Linux 的桌面应用，可完全离线运行。"} },
      { type: 'feature', text: {"en":"On the desktop your OpenRouter key is stored in the OS keychain and never reaches the page; generation requests run in the main process, free of browser CORS limits.","pt-BR":"No desktop, sua chave do OpenRouter é armazenada no chaveiro do SO e nunca chega à página; as requisições de geração rodam no processo principal, livres das limitações de CORS do navegador.","pt-PT":"No computador, a tua chave do OpenRouter é guardada no porta-chaves do sistema operativo e nunca chega à página; os pedidos de geração correm no processo principal, livres das limitações de CORS do navegador.","es":"En el escritorio, tu clave de OpenRouter se almacena en el llavero del sistema operativo y nunca llega a la página; las solicitudes de generación se ejecutan en el proceso principal, libres de las limitaciones de CORS del navegador.","ru":"На компьютере ваш ключ OpenRouter хранится в связке ключей ОС и никогда не попадает на страницу; запросы генерации выполняются в основном процессе, без ограничений CORS браузера.","it":"Sul desktop la tua chiave OpenRouter è memorizzata nel keychain del sistema operativo e non raggiunge mai la pagina; le richieste di generazione vengono eseguite nel processo principale, libere dai limiti CORS del browser.","zh":"在桌面端，你的 OpenRouter 密钥存储在操作系统钥匙串中，绝不会到达页面；生成请求在主进程中运行，不受浏览器 CORS 限制。"} },
      { type: 'feature', text: {"en":"Keyboard-navigable with a visible focus ring and screen-reader labels, and it honours your reduced-motion setting.","pt-BR":"Navegável por teclado com um anel de foco visível e rótulos para leitores de tela, e respeita sua configuração de movimento reduzido.","pt-PT":"Navegável por teclado, com um anel de foco visível e etiquetas para leitores de ecrã, e respeita a tua definição de movimento reduzido.","es":"Navegable con teclado, con un anillo de foco visible y etiquetas para lectores de pantalla, y respeta tu ajuste de movimiento reducido.","ru":"Доступна навигация с клавиатуры с видимым кольцом фокуса и подписями для программ чтения с экрана, а также учитывается ваша настройка уменьшения движения.","it":"Navigabile da tastiera con un anello di focus visibile ed etichette per screen reader, e rispetta la tua impostazione di riduzione del movimento.","zh":"支持键盘导航，带有可见的焦点环和屏幕阅读器标签，并会遵循你的减弱动态效果设置。"} },
      { type: 'feature', text: {"en":"About page with these release notes, opened from the version badge or Settings → About.","pt-BR":"Página Sobre com estas notas de lançamento, aberta a partir do selo de versão ou em Configurações → Sobre.","pt-PT":"Página Acerca de com estas notas de versão, aberta a partir do crachá de versão ou de Definições → Acerca de.","es":"Página Acerca de con estas notas de la versión, que se abre desde la insignia de versión o desde Ajustes → Acerca de.","ru":"Страница «О приложении» с этими примечаниями к релизу, открываемая из значка версии или через Настройки → О приложении.","it":"Pagina Informazioni con queste note di rilascio, aperta dal badge della versione o da Impostazioni → Informazioni.","zh":"“关于”页面，包含这些发行说明，可从版本徽章或“设置 → 关于”打开。"} },
    ],
  },
];
